dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

##############################################################################
# Here's how James does Verilator:
# 
#  # verilator
#   - sudo apt-get install verilator
#   - export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator

# maybe this should be done as before-script/before-install?
# - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator


script:

  # CGRA setup
  - echo "CGRAGenerator setup"
  - if [ "${TRAVIS_BUILD_DIR}" == "/home/travis/build/StanfordAHA/CGRAFlow" ];
    then
        cgroot=${TRAVIS_BUILD_DIR}/CGRAGenerator;
        cgbuild=${TRAVIS_BUILD_DIR}/build;
    else
        cgroot=${TRAVIS_BUILD_DIR};
        cgbuild=$cgroot/build;
        mkdir $cgbuild;
    fi

  # CGRA generate
  - echo "CGRA generate (generates CGRA + connection matrix for pnr)"
  - pushd $cgroot; ./travis-test.csh; popd

  # PNR goes here

  # Bitstream build
  - perl
        $cgroot/bitstream/bitstream_gen.pl
        $cgroot/bitstream/example/connectivity_4x4.xml
        $cgbuild/config
  - diff
        $cgroot/bitstream/example/config.dat
        $cgbuild/config.dat
        && echo PASS || echo FAIL

  # CGRA program and run (uses output of pnr)
  - echo "CGRA program and run (uses output of pnr)"
  - pushd $cgroot/verilator/generator_z_tb
  -   ./run.csh top_tb.cpp -config ../../hardware/generator_z/top_tb/tile_config.dat | tail -n 100
  - popd


#  - cd verilator/generator_z_tb
#  - ./run.csh top_tb.cpp -config ../../hardware/generator_z/top_tb/tile_config.dat

#  - export SR_VERILATOR
#  - ./run-travis.csh tb_remote.cpp

##############################################################################
##############################################################################
# NOTES
# 
# Maybe someday we'll want/need this:
# perl:
# - "5.18"
# 
# OLD
# script:
#   - which csh
#   - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

