
# We learned this weekend that Travis will load different VM configs
# depending on language settings etc. We will need to standardize on a
# config so that we can build the tools together. I recommend:
# 
# dist: trusty
# language: c
# sudo: false
# 
# Which will load Ubuntu 14. Then apt-get whatever language you need. If
# this doesn't work for you, let everyone know ASAP.

dist: trusty
language: c
# sudo: required
sudo: false





# Maybe someday we'll want/need to do this:
# perl:
# - "5.18"

# install:
#  - sudo apt-get -y --force-yes install perl
#  - sudo apt-get -y --force-yes install csh

install:
 - apt-get -y --force-yes install perl
 - apt-get -y --force-yes install csh

script:
  - which csh
  - ./travis-test.csh


# script:
#   - which csh
#   - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

