dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

install:
  # Current working directory: /home/travis/build/StanfordAHA/CGRAGenerator
  - git clone https://github.com/StanfordAHA/TestBenchGenerator.git
      --branch io-reset-padring ../TestBenchGenerator

  # Install python for testing infrastructure
  # All this just to get python3 => python3.6 or better
  # Because TBG (and LT unit tests) need python 3.6 or better
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -u -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Maybe don't need this no more b/c utest.py does it directly...?
  # # Needed by utest.py
  # - pip install --user -U pip
  # - pip install --user numpy
  # - pip install --user bit_vector

  # Needed by TestBenchGenerator
  - pip install delegator.py

script:
  # "You can sandwich the stuff in script with set -e and set +e."
  # set -e => exit on failure.
  - set -e

  ################################################################
  # Fifteen minutes for LT unit tests (background)

  # Install python dependencies
  - pip install pytest numpy delegator.py bit_vector
  - pip install git+git://github.com/phanrahan/pe.git@signed-rshift

  # Run python based tests
  - cd $TRAVIS_BUILD_DIR/tests/test_pe
  # Set env variables for genesis (installed earlier)
  - export GENESIS_HOME=/tmp/Genesis2/Genesis2Tools
  - export PATH=$GENESIS_HOME/bin:$GENESIS_HOME/gui/bin:$PATH
  - export PERL5LIB=$GENESIS_HOME/PerlLibs/ExtrasForOldPerlDistributions:$PERL5LIB

  - echo Fifteen minutes for LT unit tests
  - ../../bin/generate.csh
  - pytest >& $TRAVIS_BUILD_DIR/pytest.log &


  ########################################################################
  - echo "Twenty-five minutes (1500s) for travis system tests"
  - cd $TRAVIS_BUILD_DIR/testdir; make SILENT=TRUE travis_system_tests MEMHEIGHT=short


  ########################################################################
  # Summarize results here at the end
  - cat $TRAVIS_BUILD_DIR/pytest.log
  - grep RESULT $TRAVIS_BUILD_DIR/testdir/serpent_results.tmp | grep -v echo
