dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

##############################################################################
# Here's how James does Verilator:
# 
#  # verilator
#   - sudo apt-get install verilator
#   - export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator

# maybe this should be done as before-script/before-install?
# - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator


script:

  # CGRA setup
  - echo "CGRAGenerator setup" - `date`
  - if [ "${TRAVIS_BUILD_DIR}" == "/home/travis/build/StanfordAHA/CGRAFlow" ];
    then
        cgroot=${TRAVIS_BUILD_DIR}/CGRAGenerator;
        cgbuild=${TRAVIS_BUILD_DIR}/build;
    else
        cgroot=${TRAVIS_BUILD_DIR};
        cgbuild=$cgroot/build;
        mkdir $cgbuild;
    fi

  # CGRA generate
  - echo "CGRA generate (generates CGRA + connection matrix for pnr)" - `date`
  - pushd $cgroot; ./travis-test.csh; popd

  # PNR goes here

  # Bitstream build
  - echo "Build bitstream for programming CGRA" - `date`
  - pushd $cgroot/bitstream
  -   perl
          ./bitstream_gen.pl
          example/connectivity_4x4.xml
          $cgbuild/config
  -   ls -l example/config.dat $cgbuild/config.dat
  -   diff  example/config.dat $cgbuild/config.dat
  - popd


  # CGRA program and run ((theoretically) uses output of pnr)
  - echo "CGRA program and run (uses output of pnr)" - `date`

  - pushd $cgroot/verilator/generator_z_tb
  - ./run.csh top_tb.cpp -input io/gray_small.png
        # -config ../../hardware/generator_z/top_tb/tile_config.dat
        -config examples/config_mul2_nikhil_170323.dat
        -input io/gray_small.png 
        -output /tmp/output.raw
        -nclocks 1M
  - popd


# ./run.csh top_tb.cpp 
# -config ../../hardware/generator_z/top_tb/tile_config.dat 



#  - cd verilator/generator_z_tb
#  - ./run.csh top_tb.cpp -config ../../hardware/generator_z/top_tb/tile_config.dat

#  - export SR_VERILATOR
#  - ./run-travis.csh tb_remote.cpp

##############################################################################
##############################################################################
# NOTES
# 
# Maybe someday we'll want/need this:
# perl:
# - "5.18"
# 
# OLD
# script:
#   - which csh
#   - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

