dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

##############################################################################
# Here's how James does Verilator:
# 
#  # verilator
#   - sudo apt-get install verilator
#   - export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator

# maybe this should be done as before-script/before-install?
# - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator


script:

  # CGRA setup
  - echo CGRA setup for CGRAGenerator travis script
  - cgroot=${TRAVIS_BUILD_DIR};
  - cgbuild=${TRAVIS_BUILD_DIR}/build;
  - mkdir $cgbuild;

  # CGRA generate
  - echo "CGRA generate (generates CGRA + connection matrix for pnr)" - `date`
  - pushd $cgroot; ./travis-test.csh; popd

  # PNR goes here
  - cp $cgroot/bitstream/example3/PNRguys_mapped.xml $cgbuild/mapped.xml
  - cp $cgroot/bitstream/example3/PNRguys_io.xml     $cgbuild/io.xml

  # Bitstream build
  - echo "Build bitstream for programming CGRA" - `date`
  - cd $cgbuild
  - perl $cgroot/bitstream/example3/gen_bitstream.pl
       $cgbuild/mapped.xml
       $cgbuild/config

  # CGRA program and run ((theoretically) uses output of pnr)
  - echo "CGRA program and run (uses output of pnr)" - `date`
  - pushd $cgroot/verilator/generator_z_tb
  - ./run.csh top_tb.cpp -input io/gray_small.png
        -config $cgbuild/config.dat
        -io     $cgbuild/io.xml
        -input  io/gray.png 
        -output /tmp/output.raw
        -nclocks 3M
  - popd

# ./run.csh top_tb.cpp 
# -config ../../hardware/generator_z/top_tb/tile_config.dat 



#  - cd verilator/generator_z_tb
#  - ./run.csh top_tb.cpp -config ../../hardware/generator_z/top_tb/tile_config.dat

#  - export SR_VERILATOR
#  - ./run-travis.csh tb_remote.cpp

##############################################################################
##############################################################################
# NOTES
# 
# Maybe someday we'll want/need this:
# perl:
# - "5.18"
# 
# OLD
# script:
#   - which csh
#   - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

