dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

install:
  # - python --version
  # - sudo apt-get install python3
  # - python --version

  - pip install --user -U pip
  - pip install --user numpy
  - pip install --user bit_vector

  # pwd => /home/travis/build/StanfordAHA/CGRAGenerator
  - git clone https://github.com/StanfordAHA/TestBenchGenerator.git
      --branch master ../TestBenchGenerator

  # Install python for testing infrastructure
  # All this just to get python3 => python3.6 or better
  # Because TBG (and LT unit tests) need python 3.6 or better
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -u -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Needed by TestBenchGenerator
  - pip install delegator.py

script:
  # "You can sandwich the stuff in script with set -e and set +e."
  # set -e => exit on failure.
  - set -e

  ########################################################################
  # Twenty-five minutes for travis system tests
  - cd testdir; make SILENT=TRUE travis_system_tests MEMHEIGHT=short

  ################################################################
  # Fifteen minutes for LT unit tests

  # Install python dependencies
  - pip install pytest numpy delegator.py bit_vector
  - pip install git+git://github.com/phanrahan/pe.git

  # Run python based tests
  - cd $TRAVIS_BUILD_DIR/tests/test_pe
  # Set env variables for genesis (installed earlier)
  - export GENESIS_HOME=/tmp/Genesis2/Genesis2Tools
  - export PATH=$GENESIS_HOME/bin:$GENESIS_HOME/gui/bin:$PATH
  - export PERL5LIB=$GENESIS_HOME/PerlLibs/ExtrasForOldPerlDistributions:$PERL5LIB
  - ./run_tests.sh

  ########################################################################
  # Redo serpent summary maybe
  - grep RESULT $TRAVIS_BUILD_DIR/testdir/serpent_results.tmp
