##############################################################################
# We learned this weekend that Travis will load different VM configs
# depending on language settings etc. We will need to standardize on a
# config so that we can build the tools together. I recommend:
# 
# dist: trusty
# language: c
# sudo: false
# 
# Which will load Ubuntu 14. Then apt-get whatever language you need. If
# this doesn't work for you, let everyone know ASAP.
##############################################################################

dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

##############################################################################
# Here's how James does Verilator:
# 
#  # verilator
#   - sudo apt-get install verilator
#   - export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator

# maybe this should be done as before-script/before-install?
# - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator


script:
  - which csh
  - ./travis-test.csh
  - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator
  - cd verilator/generator_z_tb
  - ./run.csh tb_remote.cpp


#  - ./run-travis.csh tb_remote.cpp

##############################################################################
##############################################################################
# NOTES
# 
# Maybe someday we'll want/need this:
# perl:
# - "5.18"
# 
# OLD
# script:
#   - which csh
#   - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

