dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

##############################################################################
# Here's how James does Verilator:
# 
#  # verilator
#   - sudo apt-get install verilator
#   - export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator

# maybe this should be done as before-script/before-install?
# - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator


script:

  - echo "CGRAGenerator setup"
  - if [ "${TRAVIS_BUILD_DIR}" == "/home/travis/build/StanfordAHA/CGRAFlow" ];
    then
        cgroot=${TRAVIS_BUILD_DIR}/CGRAGenerator;
    else
        cgroot=${TRAVIS_BUILD_DIR};
        mkdir $cgroot/../build;
    fi

  - echo "CGRA generate (generates CGRA + connection matrix for pnr)"
  - echo $cgroot
  - pushd $cgroot
  -     ./travis-test.csh
  - popd


#  - ./travis-test.csh
#  # - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator

  # Bitstream build
#  # Note the script appends ".dat" to the end of its output filename e.g. "config" => "config.dat"
#  - if [ "${TRAVIS_BUILD_DIR}" == "/home/travis/build/StanfordAHA/CGRAFlow" ];
#    then
#        bsdir=${TRAVIS_BUILD_DIR}/CGRAGenerator/bitstream;
#    else
#        bsdir=${TRAVIS_BUILD_DIR}/bitstream;
#        mkdir ${TRAVIS_BUILD_DIR}/build;
#    fi
#  - ls -l $cgroot/bitstream/bitstream_gen.pl $cgroot/bitstream/example/connectivity_4x4.txt
  - touch ${TRAVIS_BUILD_DIR}/build/foo
  - perl
        $cgroot/bitstream/bitstream_gen.pl
        $cgroot/bitstream/example/connectivity_4x4.xml
        ${TRAVIS_BUILD_DIR}/build/config
  - diff
        $cgroot/bitstream/example/config.dat
        ${TRAVIS_BUILD_DIR}/build/config.dat
        && echo PASS || echo FAIL




#  # CGRA program and run (uses output of pnr)
#  - echo "BEGIN CGRA PROGRAM/RUN"
#  - pushd $cgroot/verilator/generator_z_tb
#  -     ./run.csh top_tb.cpp -config ../../hardware/generator_z/top_tb/tile_config.dat
#  - popd




  - cd verilator/generator_z_tb
  - ./run.csh top_tb.cpp -config ../../hardware/generator_z/top_tb/tile_config.dat

#  - export SR_VERILATOR
#  - ./run-travis.csh tb_remote.cpp

##############################################################################
##############################################################################
# NOTES
# 
# Maybe someday we'll want/need this:
# perl:
# - "5.18"
# 
# OLD
# script:
#   - which csh
#   - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

