dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

install:
  # - python --version
  # - sudo apt-get install python3
  # - python --version
  - pip install --user -U pip
  - pip install --user numpy

script:
  # set -e => exit on failure. "You can sandwich the stuff in script with set -e and set +e."
  - set -e
  #
  #
  # - cd testdir; make test_all
  #
  # BASIC TEST for new IO verilog: pointwise only 'pwv2_io.bs'
  - pushd testdir
  -   make test_basic
  -   make test_unit
  # - make SILENT=TRUE test_all
  - popd
  
# ##############################################################################
# # NOTES
# # 
# # Maybe someday we'll want/need:
# # perl:
# # - "5.18"
