dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

install:
  # - python --version
  # - sudo apt-get install python3
  # - python --version
  - pip install --user -U pip
  - pip install --user numpy
  - pip install --user bit_vector
script:
  # set -e => exit on failure. "You can sandwich the stuff in script with set -e and set +e."
  - set -e
  #
  #
  # - cd testdir; make test_all
  #
  # BASIC TEST for new IO verilog: pointwise only 'pwv2_io.bs'
  - pushd testdir
  -   make SILENT=TRUE test_basic
  -   make SILENT=TRUE test_unit
  #   make SILENT=TRUE test_serpent_dev
  -   make SILENT=TRUE test_serpent | tee serpent_results.tmp
  # - make SILENT=TRUE test_all
  - popd
  - grep RESULT $TRAVIS_BUILD_DIR/testdir/serpent_results.tmp

  # Install python for testing infrastructure
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -u -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Install python dependencies
  - pip install pytest numpy delegator.py bit_vector
  - pip install git+git://github.com/phanrahan/pe.git

  # Run python based tests
  - cd $TRAVIS_BUILD_DIR/tests/test_pe
  # Set env variables for genesis (installed earlier)
  - export GENESIS_HOME=/tmp/Genesis2/Genesis2Tools
  - export PATH=$GENESIS_HOME/bin:$GENESIS_HOME/gui/bin:$PATH
  - export PERL5LIB=$GENESIS_HOME/PerlLibs/ExtrasForOldPerlDistributions:$PERL5LIB
  - ./run_tests.sh

  
  # Redo serpent summary maybe
  - grep RESULT $TRAVIS_BUILD_DIR/testdir/serpent_results.tmp

# ##############################################################################
# # NOTES
# # 
# # Maybe someday we'll want/need:
# # perl:
# # - "5.18"
