dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

##############################################################################
# Here's how James does Verilator:
# 
#  # verilator
#   - sudo apt-get install verilator
#   - export PKG_CONFIG_PATH=/home/travis/build/jameshegarty/rigel/platform/verilator

# maybe this should be done as before-script/before-install?
# - export PKG_CONFIG_PATH=/home/travis/build/StanfordAHA/CGRAGenerator/platform/verilator


script:

  # CGRA setup
  - echo "CGRAGenerator setup" - `date`
  - if [ "${TRAVIS_BUILD_DIR}" == "/home/travis/build/StanfordAHA/CGRAFlow" ];
    then
        cgroot=${TRAVIS_BUILD_DIR}/CGRAGenerator;
        cgbuild=${TRAVIS_BUILD_DIR}/build;
    else
        cgroot=${TRAVIS_BUILD_DIR};
        cgbuild=$cgroot/build;
        mkdir $cgbuild;
    fi

  # CGRA generate
  - echo "CGRA generate (generates CGRA + connection matrix for pnr)" - `date`
  - pushd $cgroot; ./travis-test.csh; popd

  # PNR goes here
  - cp $cgroot/bitstream/example3/PNRguys_mapped.xml $cgbuild/mapped.xml

  # set bsdir = ../../bitstream
  # perl $bsdir/example3/gen_bitstream.pl $bsdir/example3/PNRguys_mapped.xml PNRCONFIG
  # set config = PNRCONFIG.dat

  # Bitstream build
  - echo "Build bitstream for programming CGRA" - `date`
  - BS_SCRIPT=$cgroot/bitstream/example3/gen_bitstream.pl
  # - PNRMAP=example/connectivity_4x4.xml
  # - PNRMAP=$cgroot/bitstream/example3/PNRguys_mapped.xml
  - PNRMAP=$cgbuild/mapped.xml
  #        
  -   perl $BS_SCRIPT $PNRMAP $cgbuild/config
  -   ls -l $cgroot/bitstream/example3/PNRguys_config.dat $cgbuild/config.dat
  -   wc -l $cgroot/bitstream/example3/PNRguys_config.dat $cgbuild/config.dat
  -   diff  $cgroot/bitstream/example3/PNRguys_config.dat $cgbuild/config.dat

  # CGRA program and run ((theoretically) uses output of pnr)
  - echo "CGRA program and run (uses output of pnr)" - `date`

  # - CGRA_CONFIG=examples/config_mul2_nikhil_170323.dat
  - CGRA_CONFIG=$cgbuild/config.dat
  - diff $cgbuild/config.dat $cgroot/verilator/generator_z/PNRCONFIG
  - pushd $cgroot/verilator/generator_z_tb
  - ./run.csh top_tb.cpp -input io/gray_small.png
        -nogen
        -config $CGRA_CONFIG
        -input io/gray.png 
        -output /tmp/output.raw
        -nclocks 3M
  - popd

# ./run.csh top_tb.cpp 
# -config ../../hardware/generator_z/top_tb/tile_config.dat 



#  - cd verilator/generator_z_tb
#  - ./run.csh top_tb.cpp -config ../../hardware/generator_z/top_tb/tile_config.dat

#  - export SR_VERILATOR
#  - ./run-travis.csh tb_remote.cpp

##############################################################################
##############################################################################
# NOTES
# 
# Maybe someday we'll want/need this:
# perl:
# - "5.18"
# 
# OLD
# script:
#   - which csh
#   - ./travis-test.csh
#   - perl -f tmp.pl
#   - hardware/generator_z/top/run.csh

