dist: trusty
language: c
sudo: false

addons:
  apt:
    # sources:
    # - ubuntu-toolchain-r-test
    packages:
      - csh
      - verilator
    # - build-essential

script:

  # CGRA setup
  - echo CGRA setup for CGRAGenerator travis script
  - cgroot=${TRAVIS_BUILD_DIR};
  - cgbuild=${TRAVIS_BUILD_DIR}/build;
  - mkdir $cgbuild;

  # CGRA generate
  - echo "CGRA generate (generates CGRA + connection matrix for pnr)" - `date`
  - pushd $cgroot; ./travis-test.csh || exit -1; popd

  # CGRA program and run uses bitstream produced by PNR guys
  - echo "CGRA program and run (uses output of pnr)" - `date`
  - pushd $cgroot/verilator/generator_z_tb
  - ./run.csh top_tb.cpp -input io/gray_small.png
        -config $cgroot/bitstream/examples/cd-swizzled.bs
        -input  io/gray.png 
        -output /tmp/output.raw
        -nclocks 3M
  - popd

##############################################################################
# NOTES
# 
# Maybe someday we'll want/need:
# perl:
# - "5.18"
